version: '3.6'

services:
  mongodb:
    image: mongo:4.4.3
    command: --replSet rs0
    container_name: mongodb-wall
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=wallfair
      - MONGO_INITDB_ROOT_USERNAME=wallfair
      - MONGO_INITDB_ROOT_PASSWORD=wallfair
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.0-alpine
    hostname: redis
    ports:
      - 6379:6379

volumes:
  mongodb:
  mongoconfig:
  postgres-data:
